6833 Update court order validation logic
bcgov/lear pull request #1161
Opened 2021-05-03 19:45 UTC by argush3

*Issue #:* /bcgov/entity#6833

Note: dependent on business-schemas PR https://github.com/bcgov/business-schemas/pull/58

*Description of changes:*

* 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

2021-05-04 05:35 UTC, thorwolpert requested changes
Please change to the common library.

2021-05-04 05:35 UTC, thorwolpert commented
Maybe mark this as Draft until we settle on what to do in the schema defintions.

2021-05-07 21:41 UTC, argush3 commented on legal-api/tests/unit/services/filings/validations/alteration/test_court_order.py
> +from datetime import datetime, timedelta
updated to use the version you referenced

2021-05-07 21:42 UTC, argush3 commented
Ready for another review whenever you have a minute @thorwolpert.  Thanks!

2021-05-07 21:45 UTC, argush3 commented
> Maybe mark this as Draft until we settle on what to do in the schema defintions.

Just noticed this...I'll put it in draft.  Actually, I'll put the schema one in draft too

2021-05-19 18:17 UTC, argush3 commented
Talked with Thor and this will be put on hold for now. More discussion needs to happen before deciding on an approach on how schema validation will look.

2021-06-03 17:49 UTC, argush3 commented
closing for now.  we can re-open if we ever need to.

2021-06-03 17:49 UTC, closed without merging