8036 duplicate message tracking tests for entity emailer
bcgov/lear pull request #1222
Opened 2021-07-05 19:21 UTC by argush3

*Issue #:* /bcgov/entity#8036

*Description of changes:*

* Added tests to verify message tracking works for following test scenarios:
  * successfully track processed message
  * does not try to re-process processed message
  * successfully track failure when exception thrown
  * failed message will succeed on retry if original error was a send email exception and email exception no longer thrown
  * retry count is properly tracked

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

2021-07-06 04:02 UTC, vysakh-menon-aot approved these changes

2021-07-07 23:02 UTC, thorwolpert requested changes
tracker should be in its own fixture

2021-07-07 23:02 UTC, thorwolpert commented on queue_services/entity-emailer/tests/conftest.py
> +def db(app, tracker_app):  # pylint: disable=redefined-outer-name, invalid-name
tracker should be its own fixture

2021-07-09 22:51 UTC, argush3 commented on queue_services/entity-emailer/tests/conftest.py
> +def db(app, tracker_app):  # pylint: disable=redefined-outer-name, invalid-name
moved tracker_db to own fixture

2021-07-09 22:52 UTC, argush3 commented
@thorwolpert ready for another look.  thanks!

2021-07-13 22:58 UTC, thorwolpert approved these changes

2021-07-13 22:58 UTC, merged