7388 changed to cloud event msg type
bcgov/lear pull request #1236
Opened 2021-07-26 10:09 UTC by vysakh-menon-aot

*Issue #:* /bcgov/entity#7388

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

2021-07-27 20:21 UTC, argush3 commented on queue_services/entity-emailer/src/entity_emailer/email_templates/NR-REFUND.html
> +              purchase, you will recieve a refund to your PAD account within 10 to 14 business days.
typo on `recieve`

2021-07-27 20:45 UTC, andrepestana-aot requested changes

2021-07-27 20:45 UTC, andrepestana-aot commented on queue_services/entity-emailer/src/entity_emailer/email_templates/NR-REFUND.html
> +              purchase, you will recieve a refund to your PAD account within 10 to 14 business days.
According to https://www2.gov.bc.ca/gov/content/governments/services-for-government/service-experience-digital-delivery/web-content-development-guides/web-style-guide/writing-guide/numbers the time format should be `7:00 pm Pacific time`

2021-07-27 20:59 UTC, argush3 requested changes
looks good.  The one typo.

And also, would you be able to add the parameterized queue message payload for this email to the `test_should_successfully_process_valid_messages_for_all_supported_message_types` test in `/tests/unit/test_tracker.py`?  I just wanted to keep the happy path tracker test up to date for all the different type of queue message payloads we have coming in.

2021-07-28 13:21 UTC, argush3 approved these changes

2021-07-29 15:34 UTC, andrepestana-aot approved these changes

2021-07-29 15:35 UTC, merged