9016 - Updated dissolution filer
bcgov/lear pull request #1333
Opened 2021-11-16 22:22 UTC by andrepestana-aot

*Issue #:* /bcgov/entity#9016
*Description of changes:*

- updated dissolution filer processor; 
- added tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

2021-11-17 18:42 UTC, argush3 requested changes
I think we need to add a processor for special resolutions for COOP voluntary dissolutions.  I'm thinking it might only require adding meta data to the filing.

2021-11-23 17:20 UTC, thorwolpert reviewed
couple of small changes

2021-11-23 17:20 UTC, thorwolpert commented on queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
>      # remove all directors and add custodial party if in filing
Could you do me favour and change this comment, directors are not removed and the custodian is added.
It's different than the other party updates.

2021-11-23 17:20 UTC, thorwolpert commented on queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
> +    if filing['business']['legalType'] == Business.LegalTypes.COOP.value:
you don't need to add the ```.value```

2021-11-23 17:23 UTC, thorwolpert commented
Re: meta additions, that would be good to place the sub-type of the dissolution there for the ledger and other views.

2021-11-23 19:14 UTC, closed without merging

2021-11-23 19:14 UTC, andrepestana-aot commented
Sorry, I messed up the branch. I created a fresh one: https://github.com/bcgov/lear/pull/1343