Filer fix - Dissolution processor deleting existing party info
bcgov/lear pull request #1363
Opened 2021-12-08 20:58 UTC by lekshmimallika-aot

*Issue #:* /bcgov/entity###

*Description of changes:*
Added an optional argument to update parties method to indicate whether parties should be deleted and created or just appended.
Updated test 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

2021-12-08 21:33 UTC, argush3 requested changes
looks good but can we add all the other corp types to parametrized tests?  i.e. ULC, CCC and BEN

2021-12-08 22:12 UTC, argush3 approved these changes

2021-12-08 22:12 UTC, argush3 commented
thanks, looks good!

2021-12-09 07:36 UTC, vysakh-menon-aot approved these changes

2021-12-09 16:30 UTC, merged