12261 - rewired http-logging through LD
bcgov/lear pull request #1778
Opened 2022-10-31 20:17 UTC by MatthewCai2002

*Issue #12261:* : https://www.github.com/bcgov/entity/issues/12261

*Description of changes:*
    - rewired disabling and enabling of http-logging through LD feature flag

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

2022-11-01 01:32 UTC, seeker25 commented
I think we should make the changes somewhere else, making a dependency on flask here doesn't make sense

2022-11-01 17:07 UTC, kialj876 requested changes
Hey Mathew Thor is rolling in a flag service today that should be used here I think. Can you connect with him? This is the code he's bringing in https://github.com/thorwolpert/flask-ld-logger -- not sure where it'll live though

2022-11-01 17:07 UTC, kialj876 commented on queue_services/common/src/entity_queue_common/service_utils/service_logger.py
> +enable_logging = flag_service.value('http-log-enable')
Could you grab this flag name from a config value that defaults to this so that we can different queues that share the same ld project?

2022-11-01 17:12 UTC, MatthewCai2002 commented on queue_services/common/src/entity_queue_common/service_utils/service_logger.py
> +from legal_api.services import Flags
yeah I agree. I'll connect with Thor to see how to use that new flag service

2022-11-02 21:37 UTC, MatthewCai2002 commented
Looks like we're going to move to a new queue service at the end of November, going from "pull client" to a "push client", gonna leave this PR alone until that's done

2022-11-17 19:39 UTC, closed without merging