updated limited restoration extension expiry date
bcgov/lear pull request #1995
Opened 2023-04-12 22:25 UTC by kzdev420

*Issue #:* /bcgov/entity#15915

*Description of changes:*

Fix limitedRestorationExtension.expiry_date (3 -> 2 years)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

2023-04-12 22:59 UTC, vysakh-menon-aot requested changes

2023-04-12 22:59 UTC, vysakh-menon-aot commented on legal-api/src/legal_api/services/filings/validations/restoration.py
> +        if restoration_type == 'limitedRestoration': now = LegislationDatetime.now().date()
`restoration_expiry_date` will be null while filing a `limitedRestoration`.
```suggestion
        now = LegislationDatetime.now().date()
        if restoration_type == 'limitedRestorationExtension': 
            now = LegislationDatetime.as_legislation_timezone(business.restoration_expiry_date).date()
```

2023-04-12 22:59 UTC, vysakh-menon-aot commented on legal-api/tests/unit/services/filings/validations/test_restoration.py
> +    business = Business(identifier='BC1234567', legal_type='BC', restoration_expiry_date=LegislationDatetime.now())
Add test to consider above comment (by setting `restoration_expiry_date` to None when `restoration_type` is `limitedRestoration`)

2023-04-13 18:53 UTC, argush3 approved these changes

2023-04-13 19:44 UTC, merged