20164-updated-alternate-names-table
bcgov/lear pull request #2512
Opened 2024-03-13 20:46 UTC by jamespaologarcia

*Issue #:* /bcgov/entity#20164

- Added entity_type to alternate_names & alternate_names1 tables to [alembic script](https://github.com/bcgov/lear/blob/2c24dbfce1c37bc78d1af75cdace2c829a5c8ee0/legal-api/migrations/versions/004f7558063f_second.py#L940).
- Added an index for entity_type field
- Ensured downgrade script is added too

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache 2.0).

2024-03-13 21:37 UTC, chenhongjing requested changes
Can you do the same things for `alternate_names_history` table?

2024-03-13 21:50 UTC, jamespaologarcia commented
Making some updates. To address errors when running the upgrade.

2024-03-14 17:20 UTC, argush3 commented on legal-api/migrations/versions/004f7558063f_second.py
> +        batch_op.create_foreign_key('fk_entity_type', 'legal_entities', ['entity_type'], ['entity_type'])
don't need a FK for `entity_type`

2024-03-14 17:21 UTC, argush3 commented on legal-api/migrations/versions/004f7558063f_second.py
> +        batch_op.drop_constraint('fk_entity_type', type_='foreignkey')
don't need this FK

2024-03-14 19:31 UTC, jamespaologarcia commented
![image](https://github.com/bcgov/lear/assets/17242795/5662abbd-baae-4314-a3e1-fa6e81b4cf78)

2024-03-14 20:28 UTC, JazzarKarim approved these changes
LGTM

2024-03-14 20:41 UTC, chenhongjing approved these changes
LGTM

2024-03-14 20:52 UTC, merged